### ISSUE TITLE
SSE Client identification

### ISSUE THREAD

**Issue by robtweed** [bunsvr/utils#4]
The SSE documentation is extremely sparse and difficult to understand how to apply this functionality (I'm familiar with Fastify's SSE interface however, so I know how SSE can be used).

One thing I'd need to be able to do is to identify/recognise the individual connected clients - in Fastify that's done through req.id.  Does Stric provide anything similar?

Also could you expand on how to use req.controller? Some simple examples would help

**Comment by aquapi** [comment]
@robtweed This is just a polyfill and i didn't document it either
You shouldn't use it
Rn you can wrap the response with a readable stream

**Comment by aquapi** [comment]
@robtweed dave is doing something like `EventSource` for it
My implementation is really bad so I didn't put it in the new docs
https://stricjs.netlify.app/

**Comment by robtweed** [comment]
No problem - I'll await with interest.  As I say I'm familiar with and make use of the Fastify SSE module.  SSE is one of the lesser known Web Platform capabilities that is actually very useful and powerful once you "get it", so I definitely think it's worth providing access to in Stric

**Comment by aquapi** [comment]
@robtweed I'm gonna open this until something like `EventSource` is implemented.

**Comment by aquapi** [comment]
@robtweed New SSE API is available in `@stricjs/app` [docs](https://stricjs.netlify.app/docs/basics/app.html#streaming).
