### ISSUE TITLE
stream types missing in >= 2.0.6 after installing

### ISSUE THREAD

**Issue by jopek** [bunsvr/utils#5]
I was following the quick start at https://bun.sh/guides/ecosystem/stric and encountered the following error:
`SyntaxError: Export named 'dir' not found in module '/......./node_modules/@stricjs/utils/index.js'.`

changing the dependencies in package.json:
- `"@stricjs/utils": "2.0.7"`
  - `bun i`
  - `find node_modules/@stricjs/utils/types | grep stream` ==> nothing found
- `"@stricjs/utils": "2.0.6"`
  - `bun i`
  - `find node_modules/@stricjs/utils/types | grep stream` ==> nothing found
- `"@stricjs/utils": "2.0.5"`
  - `bun i`
  - `find node_modules/@stricjs/utils/types | grep stream` ==> 🎉  `node_modules/@stricjs/utils/types/stream.d.ts`

With `"@stricjs/utils": "2.0.5"` there's no such error.

Did I miss something or is it a bug?

**Comment by brynne8** [comment]
Hi the doc on bun ecosystem page is outdated and stricjs has many breaking changes since then. If you want to try stric, then refer to the latest doc at https://stricjs.netlify.app/docs/app/

**Comment by aquapi** [comment]
@jopek The project has been scrapped. Please check out my new framework here: https://www.npmjs.com/package/@bit-js/byte
